version: "3.9"

services:
  app-api_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-dev
    ports:
      - "4000:3000"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4000/",
        ]
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
