###Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "studentId": "22222",
    "firstName": "hamdan",
    "lastName": "Cawasa",
    "email": "cawasa1@gmail.com",
    "phoneNumber": "1234567890",
    "password": "Cawasa@123",
    "role": "admin"
}

###Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "anthony.dev@gmail.com",
    "password": "Anthony@123"
}

###Log out
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODZmMDlmYzI4YTk5MTVkNThmYTc3Y2QiLCJlbWFpbCI6ImFudGhvbnkuZGV2QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjExNzM5NiwiZXhwIjoxNzUyMTE3NDExfQ.MLMJ4QXM5sHmgBMLTXxgHYxn1oKAhvL4p_u2pccQd04

###Access Token
GET http://localhost:8080/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODZmMDlmYzI4YTk5MTVkNThmYTc3Y2QiLCJlbWFpbCI6ImFudGhvbnkuZGV2QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjEwODAwMCwiZXhwIjoxNzUyMTA4MDE1fQ.jpA4NlNlA0tiSZucMmo5MvGmzEacbHOMYkMjyNjABaE

###Refresh Token
POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODg3MzI2MzUxMTQ2N2FhOThmYzJlYTgiLCJlbWFpbCI6ImFudGhvbnkuZGV2QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1Njc3NjA5NywiZXhwIjoxNzU2Nzc2MTA3fQ.fPyuVUlwFGzDp36Pe2KqzsFFSdDn3bx9TsX87wM78c0"
}

###Profile
GET http://localhost:8080/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODg3MzI2MzUxMTQ2N2FhOThmYzJlYTgiLCJlbWFpbCI6ImFudGhvbnkuZGV2QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NjgwMTQ5MywiZXhwIjoxNzU2ODAyMzkzfQ.wKPPd1flSUfkugEKyPhNubuQOG9gpi9cVvw_ZcTc6eE